version: "3"
services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    
  app:
    build:
      context: ./
    links:
      - postgres:postgres
      - redis:redis
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    ports:
      - 3000:3000
      - 4000:4000